version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:Vikas@2324@localhost:5432/todo-app
  
  frontend:
    build: 
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        - DB_URL=postgresql://postgres:Vikas@2324@localhost:5432/todo-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:Vikas@2324@localhost:5432/todo-app

  webcoket:
    build: 
      context: .
      dockerfile: docker/Dockerfile.webcoket
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://postgres:Vikas@2324@localhost:5432/todo-app

    