FROM node:22-alpine

RUN npm i -g bun

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

WORKDIR /app

COPY ./bun.lock ./bun.lock
COPY ./package*.json ./
COPY ./turbo.json ./turbo.json

RUN bun install

COPY ./packages ./packages
COPY ./apps/web ./apps/web  

RUN echo $DATABASE_URL 

RUN bun run db:generate
RUN bun run build

EXPOSE 3000

CMD ["bun", "run", "start:web"]
